### ISSUE TITLE
Install WSL2 update broke WSL2

### ISSUE THREAD

**Issue by dbuteau** [MicrosoftDocs/WSL.fr-FR#14]
Hello!
My WSL2 was working nice since months (W10 build 19631.1).
My Docker desktop got an update, and no more working (wsl timeout).
Searching for solution i found someone saying to follow this page (https://aka.ms/wsl2kernel) were it say to install the wsl_update_x64.msi
Since the installation of this is done, my wsl2 no more want to work at all, the error message is: 
> WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel

Tried to:
- deactivating Hyperv
- Uninstall Ubuntu/Reinstall
- Launch repair; uninstall/reinstall the Wsl_update

Nothing work.
What can i do?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 5d720f69-aff2-38d8-f0c6-9909e94acaa2
* Version Independent ID: 9d121625-e741-6d20-f3de-201a939290b8
* Content: [Mise à jour du noyau Linux WSL 2](https://docs.microsoft.com/fr-fr/windows/wsl/wsl2-kernel)
* Content Source: [WSL/wsl2-kernel.md](https://github.com/MicrosoftDocs/WSL.fr-fr/blob/live/WSL/wsl2-kernel.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by dbuteau** [comment]
Ok i've found than you need to create .wslconfig file in c:/users/me/ and only then you can reinstall the distribution and launch wsl/terminal you should add this information

**Comment by craigloewen-msft** [comment]
You shouldn't require having the .wslconfig file in C:\users\me . The error is indicating that you're missing a Linux kernel itself, so installing and reinstalling the WSL_update.msi file should have put you on the right path.

If you run into this again please let me know and send over any debug or repro steps as I'd love to dive into it. Thank you for filing!
