### ISSUE TITLE
you don't need to translate "curl" into "boucle"

### ISSUE THREAD

**Issue by biteuljiouce** [MicrosoftDocs/WSL.fr-FR#2]
"Télécharger à l’aide de la boucle" doesn't mean anything in french.
Please keep the original name of the app "curl".
thx !

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Télécharger manuellement le sous-système Windows pour Linux (WSL) distributions](https://docs.microsoft.com/fr-fr/windows/wsl/install-manual#feedback)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/WSL.fr-fr/blob/live/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by srvbpigh** [comment]
Hello, @biteuljiouce
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @biteuljiouce 

Thank you for your feedback. The page in question has been machine-translated, which is not always perfectly understandable. We recently added a "Read in English" option on the right which allows you to switch to the English version without having to change the language settings.

Microsoft DOCS International Team
Kind regards,
