### ISSUE TITLE
French navigation title of wsl2-ux-changes is badly translated

### ISSUE THREAD

**Issue by echoix** [MicrosoftDocs/WSL.fr-FR#4]
The title at the navigation bar is "Passage de l’expérience utilisateur de WSL 1 à WSL 2" while the title of the article is "Modification de l’expérience utilisateur entre WSL 1 et WSL 2". The article title is a good translation of "User Experience Changes Between WSL 1 and WSL 2", but the navigation title on the left is not a good translation for "User Experience Changes from WSL 1 to WSL 2".

It should look like the article title to be correct.

---
#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour docs.microsoft.com ➟ problème de liaison GitHub.*

* ID: d8787d64-a0f4-613d-6d9c-1a27bb2f6735
* Version Independent ID: 520a7c39-72fa-28c1-e54d-6d845087c309
* Content: [Modifications de l’expérience utilisateur entre WSL 1 et WSL 2](https://docs.microsoft.com/fr-ca/windows/wsl/wsl2-ux-changes)
* Content Source: [WSL/wsl2-ux-changes.md](https://github.com/MicrosoftDocs/WSL.fr-fr/blob/live/WSL/wsl2-ux-changes.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by srvbpigh** [comment]
Hello, @echoix
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Bonjour @echoix

Merci pour votre feedback. 

Notre équipe linguistique a examiné vos suggestions de traduction et les a acceptées. Nous avons modifié les articles concernés selon vos suggestions et les avons republiés sur les pages https://docs.microsoft.com/fr-ca/windows/wsl/wsl2-ux-changes du site Docs.  

Votre contribution à nos articles est grandement appréciée. Nous vous encourageons donc à continuer d’envoyer vos commentaires à Microsoft. 

Cordialement, 
L’équipe Microsoft DOCS International
