### ISSUE TITLE
Problème d'affichage

### ISSUE THREAD

**Issue by ltajazz** [MicrosoftDocs/WSL.fr-FR#7]
Bonjour.
Il y a un problème d'affichage sur le chapitre "Installer le package de mise à jour du noyau Linux".
On voit le code html brut:
 &lt;span data-ttu-id="3e2f5-111"&gt;Exécutez le package de mise à jour téléchargé à l’étape précédente.&lt;/span&gt;&lt;span class="sxs-lookup"&gt;&lt;span data-stu-id="3e2f5-111"&gt;Run the update package downloaded in the previous step.&lt;/span&gt;&lt;/span&gt;

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 5d720f69-aff2-38d8-f0c6-9909e94acaa2
* Version Independent ID: 9d121625-e741-6d20-f3de-201a939290b8
* Content: [Mise à jour du noyau Linux WSL 2](https://docs.microsoft.com/fr-fr/windows/wsl/wsl2-kernel#feedback)
* Content Source: [WSL/wsl2-kernel.md](https://github.com/MicrosoftDocs/WSL.fr-fr/blob/live/WSL/wsl2-kernel.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by srvbpigh** [comment]
Hello, @ltajazz
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Bonjour @ltajazz 

Merci pour votre contribution. Notre équipe a examiné vos commentaires et il semble que ce problème ait déjà été signalé.  

Je vous invite à consulter le problème https://github.com/MicrosoftDocs/WSL/issues/596
Pour éviter un doublon, nous avons clos le problème que vous nous avez signalé.  

Cordialement,  

L’équipe Microsoft DOCS International
