### ISSUE TITLE
problèmes

### ISSUE THREAD

**Issue by maxiem** [MicrosoftDocs/WSL.fr-FR#8]
j'ai bien suivi les instructions afin de réinitialiser le mdp cependant lorsque que j'utilise sudo et qu'on me demande ce mdp on m'indique qu'il est faux. 
Je ne sais pas comment faire...
Merci d'avance

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 9a09359b-8092-fb08-353c-ae03a91f26b6
* Version Independent ID: 6a9228f4-5240-8b14-3077-00340bcfdcf1
* Content: [Créer et mettre à jour des comptes d’utilisateur pour les distributions WSL](https://docs.microsoft.com/fr-fr/windows/wsl/user-support?redirectedfrom=MSDN#feedback)
* Content Source: [WSL/user-support.md](https://github.com/MicrosoftDocs/WSL.fr-fr/blob/live/WSL/user-support.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by srvbpigh** [comment]
Hello, @maxiem
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Bonjour @maxiem 

Votre contribution est très appréciée. Ces commentaires concernant un produit, nous vous invitons à enregistrer votre suggestion en utilisant le bouton «Envoyer des commentaires sur le produit » qui se trouve au bas de la page DOCS. 

Si vous avez des commentaires relatifs à la documentation, n'hésitez pas à les communiquer par ce canal. 

Nous apprécions réellement votre contribution à nos articles. 

L’équipe internationale de Microsoft DOCS
